on:
  - pull_request
  - push

name: Install

jobs:
  run:
    name: Tests

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Ensure zsh
        if: matrix.operating-system == 'ubuntu-latest'
        run: |
          if ! command -v zsh >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y zsh
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: ./install.sh
